### ISSUE TITLE
Initialization fails on windows (and probably on any non-linux environment)

### ISSUE THREAD

**Issue by velkrissz** [Clashkid155/size#2] opened 2022-03-02 11:39 UTC
The Sizes constructor fails to run due to LateInitializationError: Field '_libraryPath' in version 1.0.4.
Your constructor implementation initializes a `late final` field with: `_libraryPath = 'libsize.so';` then tries to change it depending on the current platform.  You can not override an already initialized final field.

My suggestion: You should put the default value to an else branch or even better: throw an error/exception on unsupported platforms.

I would make a pull request with a quick fix, but I have no linux/mac devices to test it.

**Comment by Clashkid155** [comment] 2022-03-03 10:46
Thanks for this. 
I did fix it but since i don't actually use windows (vm on Linux), it's quite hard testing and i forgot to push it.
Pull request is welcomed, i can test on Linux.

**Comment by vkrissz** [comment] 2022-03-03 13:48
I forked the repo and managed to make it work on windows and WSL ubuntu. Using `dart example/size_example.dart`.
You can check it here: https://github.com/vkrissz/size
I'm pretty new to dart/flutter so I'm not sure I made the correct changes, this is why I have not created a PR.
One thing that I think won't work: the native implementations are loaded from the disk and are not included with the lib. This is why I needed to change the `_libraryPath`.

**Comment by Clashkid155** [comment] 2022-03-03 15:57
Are you using flutter or only dart? 
Your changes looks good but I'm not too sure about the removal of `flutter` from `pubspec.yaml`.

It's not implemented natively.

The plugin makes use of dart ffi which seems to give flutter issues when adding them to your app.

When using dart only, those lib's(*.so and *.dll) in the lib folder are used in your project while on flutter those lib's are recompiled and added to the build. You can check this in the various build folder.


By the way, hope the plugin satisfies  your use case?

**Comment by vkrissz** [comment] 2022-03-04 10:27
The flutter part seemed bad for me as you mentioned in the readme that the package does not depend on flutter. Especially as `dart pub get` failed to execute while `flutter pub get` executed fine.

I have no experience with native compilation thus I was not able to run the `cmake` command. Similarly, no experience with the `ffi`. 

I wanted to use the package in a dart-only, self-contained CLI app that will be compiled for the 3 desktop environments. Unfortunately, I had to remove it as it was not able to initialize. (Only a nice-to-have feature.)
I would give it another try if you could release a new version with a proper constructor invocation. (My paths are probably wrong.)

**Comment by Clashkid155** [comment] 2022-03-04 23:15
I think i might split the package into flutter and dart versions.
I haven't tested this on Mac(Don't have) only on Linux and Windows. Unfortunately you have to compile the lib for Mac if you want to use it.

**Comment by Clashkid155** [comment] 2022-03-05 00:12
I just released an update, try using `size: ^1.0.4-1`. Hopefully it's up within a few hours.

**Edit**
Well this update didn't solve the problem either.

Can you just take the need lib(*.so and *.dll) and add them to your bin or lib directory?

**Comment by vkrissz** [comment] 2022-03-07 11:26
First of all, thanks for the new release!
I tried it again but there are some issues.

1. The constructor name `Size` and the class name `Sizes` are inconsistent. Calling `Sizes()` won't run the dynamic lib loading code. Instead I had to call `Sizes()..Size()` to achieve it. (Otherwise, it throws LateInitializationError.)
2. The native lib is required to be present as you mentioned but it needs to be placed next to the compiled executable. (Placing them to the bin directory does not include them or at least it failed to load it from there.)

Unfortunately, requiring extra native files is not acceptable for my use case. These native libs must be included in the executable. Is there a way to include it like flutter's assets folder?

**Comment by Clashkid155** [comment] 2022-03-07 14:18
Can i get a screenshot of your error? 

In dart(so far) there's no possible way to include the lib with the package so you have to download them yourself or i somehow automate the download (trying that now).

Is your code open source? So i can test it myself. 

I would also like to know how you compile your program.

I've actually been on this issue since you reported it, trying my best to resolve it fast.

**Comment by vkrissz** [comment] 2022-03-07 15:25
Unfortunately, I have no permission to release the code at this point, be hoping it will be open source in the future.
I created a minimal project with the reproduction steps in the readme: https://github.com/vkrissz/size_test

Constructor error output (1):
```
PS D:\projects\size_test> .\build\cli.exe
Unhandled exception:
LateInitializationError: Field '_dylib@15084592' has not been initialized.
#0      Sizes.getAvailableDiskSpace (package:size/size.dart)
#1      main (file:///d:/projects/size_test/bin/cli.dart:11)
#2      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295)
#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192)
```

Lib not found error output (2):
```
PS D:\projects\size_test> .\build\cli.exe
Unhandled exception:
Invalid argument(s): Failed to load dynamic library 'size.dll': error code 126
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:12)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:23)
#2      Sizes.Size (package:size/size.dart:25)
#3      main (file:///d:/projects/size_test/bin/cli.dart:8)
#4      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192)
```

**Comment by vkrissz** [comment] 2022-03-07 15:34
You're really nice, but you don't have to solve my lib include problem. If this becomes mandatory, I will do it myself. 
(On the other hand, downloading might work, but it is not in the scope of this lib.)

**Comment by Clashkid155** [comment] 2022-03-08 00:10
Please check the latest version `size: ^1.0.5+1`.
I believe all issues should be fixed there.

The constructor error was me forgetting to change the class name everywhere which significantly affected me while debugging.
Hopefully it works well now.

**Closed as completed** 2022-03-14 16:34 UTC
Labels: bug
